---
- name: Configure Kubernetes nodes
  hosts: all
  become: true

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "../../environments/{{ cluster_environment }}/vars.yaml"

  roles:
    - common
    - container_runtime
    - kubernetes


- name: Configure Kubernetes control plane
  hosts: control_plane
  become: true

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "../../environments/{{ cluster_environment }}/vars.yaml"

  roles:
    - control_plane
    - helm
    - cni

- name: Join Kubernetes workers
  hosts: workers
  become: true

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "../../environments/{{ cluster_environment }}/vars.yaml"

  roles:
    - worker

- name: Configure Longhorn storage nodes
  hosts: longhorn_storage
  become: true

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "../../environments/{{ cluster_environment }}/vars.yaml"

  roles:
    - longhorn_storage


- name: Install Longhorn
  hosts: control_plane
  become: true

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "../../environments/{{ cluster_environment }}/vars.yaml"

  roles:
    - longhorn
